---
## ###########
## frontmatter and metadata data
## ###########
## blindreview: on
title: 'Título principal'
subtitle: 'Algum subtítulo vem aqui'
titlerunning: 'Título curto'
author: 
    - name: Nome1 Sobrenome1
      email: nome1@institution.org
      affiliation: University of Knowledge
university:
    name: Universidade Estadual de Campinas
    institute: Instituto de Filosofia e Ciências Humanas
    logo: logo-unicamp.eps
    city: Campinas
institute: "Universidade Estadual de Campinas"
thanks: "Grants or other notes in front page"

abstract: 'Será possível escrever um abstract enorme em uma simples propriedade yaml? Acho meio estranho... Enfim.'

keywords: '\textbf{Palavras-chave: }um; dois; três.'

## ####################
## template variables
## ####################
documentclass: scrartcl

geometry: "top=3cm, bottom=2cm, left=3cm, right=2cm"

## lang for pandoc-citeproc
lang: pt-BR
## lang for polyglossia
polyglossia-lang:
    name: brazil
polyglossia-otherlangs:
    name: english

## default font values
fontenc: T1
fontfamily: lmodern
fontsize: 12pt

papersize: a4

indent: '2.0cm'
linestretch: 1.5

## toc-depth: 3

## ###############################
## pandoc-crossref customizations
## ###############################
figureTitle: "Figura"
tableTitle: "Tabela"
listingTitle: "Lista"
figPrefix: "figura"
eqnPrefix: "equação"
tblPrefix: "tabela"
lstPrefix: "lista"
loftitle: "# Lista de figurassss"
lotTitle: "# Lista de tabelas"

---