---
author-meta: Nome Sobrenome
title-meta: 'Título principal: aqui vem o título da tese'
subject-meta: Assunto
university:
    name: Universidade Estadual de Campinas
    institute: Instituto de Filosofia e Ciências Humanas
    logo: logo-unicamp.eps
    city: Campinas

## lang for pandoc-citeproc
lang: pt-BR
## lang for polyglossia
polyglossia-lang:
    name: brazil
polyglossia-otherlangs:
    name: english

## default font values
fontfamily: lmodern
fontsize: 12pt

papersize: a4

indent: '2.0cm'
## toc-depth: 3
---